### ISSUE TITLE
Check if stock sync is enabled

### ISSUE THREAD

**Issue by tsalumets** [KonektOU/merit-aktiva-for-woocommerce#1]
https://github.com/KonektOU/merit-aktiva-for-woocommerce/blob/247abc4f4b3e2c42008f4b97b17ae5a4773c24d8/includes/Orders.php#L319

Had some debugging why my store gave error at checkout validation for product not in stock. Reason was this method. Would it make sense to check if stock sync enabled before validating product against Merit products.

**Comment by RistoNiinemets** [comment]
Thanks, @tsalumets! Added check to version 1.0.32
